server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog
    username: root
    password: jym960429
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    # 文件上传
    multipart:
      # 单个上传文件的最大允许大小
      max-file-size: 20MB
      # HTTP请求中包含的所有文件的总大小的最大允许值
      max-request-size: 20MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKey: "OFnzRN4eTaCp29WgKy4mXD0Qk3fkAXIXkM79aOj1"
  secretKey: "wQDZoVHSf-NxeLr9VmxjSmjMv2px-eWmbFAUIGJX"
  bucket: "dawn-myblog"