server:
  port: 7777

spring:
  # 数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/myblog
    username: root
    password: jym960429
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    # 文件上传
    multipart:
      # 单个上传文件的最大允许大小
      max-file-size: 20MB
      # HTTP请求中包含的所有文件的总大小的最大允许值
      max-request-size: 20MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  #注释掉mybatisplus的日志信息，避免对我们的日志信息造成干扰
  #  configuration:
  #    # 日志
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除的字段
      logic-delete-field: delFlag
      # 代表已删除的值
      logic-delete-value: 1
      # 代表未删除的值
      logic-not-delete-value: 0
      # 主键自增策略，以mysql数据库为准
      id-type: auto


oss:
  accessKey: "OFnzRN4eTaCp29WgKy4mXD0Qk3fkAXIXkM79aOj1"
  secretKey: "wQDZoVHSf-NxeLr9VmxjSmjMv2px-eWmbFAUIGJX"
  bucket: "dawn-myblog"